---
title: "fairenough_pipeline"
format: html
---

# Clean data

```{r}
dir.create("data-raw", showWarnings = FALSE)
# Add data to data-raw
```

```{r}
dataframes_raw <- list.files("data-raw", pattern = "\\.csv$", full.names = TRUE)
dataframes_raw <- dataframes_raw[!basename(dataframes_raw) %in% "dictionary.csv"]

for (f_path in dataframes_raw) {
  fairenough::process_csv(f_path)
}
```

# Pipeline

```{r}

# USER SETUP
root_name <- basename(here::here())

organisation <- "Global-Health-Engineering"

authors <- list(
  list(given = "Nicolo", family = "Massari", role = c("aut", "cre"), email = "nmassari@ethz.ch", ORCID = "0009-0006-8421-930X", affiliation="ETH Zurich"), 
  list(given = "Lars", family = "Schöbitz", role = c("aut", "ctb"), email = "lschoebitz@ethz.ch", ORCID = "0000-0003-2196-5015", affiliation="ETH Zurich"), 
  list(given = "Elizabeth", family = "Tilley", role = c("aut", "fnd"), email = "tilleye@ethz.ch", ORCID = "0000-0002-2095-9724", affiliation="ETH Zurich")
)

title = "ETH Board Open Research Data (ORD) Program Project Metadata and Report Data"

description = "This data package contains metadata and report data from 96 research projects funded by the joint Open Research Data (ORD) program of ETH Zurich, EPFL, and the four research institutes of the ETH Domain. The package includes project-level metadata, such as project titles, descriptions, and categorizations (Establish, Explore, Contribute), as well as data extracted from reports submitted by each project, providing insights into the projects' objectives, methods, outcomes, and impacts."

# CONSTANTS
license <- "cc-by-4.0"

dictionary_path <-  here::here("data-raw", "dictionary.csv")

dataframes <- list.files("inst/extdata", pattern = "\\.csv$", full.names = TRUE)
dataframes <- dataframes[!basename(dataframes) %in% "dictionary.csv"]
```

```{r}
fairenough::setup_dictionary()

# TODO
# fairenough::gendict() # APIKEY, dataset, context

fairenough::setup_roxygen(title = title, description = description)

desc::desc_del_author()

for (i in seq_along(authors)) {
  aut <- authors[[i]]
  usethis::use_author(
    given = aut$given, 
    family = aut$family, 
    role = aut$role, 
    email = aut$email,
    comment = c(ORCID = aut$ORCID),
  )
}

fairenough::update_description(organisation = organisation, title = title, description=description)

fairenough::add_metadata()
fairenough::update_metadata()
fairenough::add_creator(name=paste(aut$given, aut$last, sep=" "), 
            email=aut$email, 
            affiliation=aut$affiliation) # Get from use_author
fairenough::generate_jsonld()

# TODO
# create_zenodo_json()

fairenough::setup_readme()
fairenough::setup_website()
```

```{r}
devtools::document()
devtools::check()
devtools::install()

devtools::build_readme()
devtools::build_site()
```

```{r}
doi = "10.5281/zenodo.15554776"
fairenough::update_citation(doi) # TODO, automatically delete current doi before updating
```